In [1]:
import numpy as np

In [2]:
x=np.arange(2,6).reshape(4)

In [ ]:
x

array([2, 3, 4, 5])

In [3]:
p=np.arange(4,8)

In [4]:
p

array([4, 5, 6, 7])

In [6]:
c=np.arange(2,10).reshape(2,4)

In [ ]:
c

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [ ]:
c=np.arange(2,10).reshape(4,2)

In [ ]:
c

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
x=np.arange(24).reshape(4,3,2)

In [ ]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
list1=[1,2,3]

In [ ]:
arr1 = np.array(list1)

In [ ]:
list1

[1, 2, 3]

In [ ]:
arr2=np.array([[1,4,5],[44,55,66]])
arr2

array([[ 1,  4,  5],
       [44, 55, 66]])

In [ ]:
arr3=np.arange(24).reshape(4,3,2)

In [ ]:
arr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
arr3=np.array([[[1,2,3],[4,5,6]]])

In [ ]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
arr3.shape(2)

TypeError: 'tuple' object is not callable

In [ ]:
list1

[1, 2, 3]

In [ ]:
arr1.shape

(3,)

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr3=np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
arr3.dtype

dtype('int64')

In [ ]:
list1.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
K=nnp.array(['1','2','3'])

In [ ]:
K.dtype

dtype('<U1')

In [ ]:
K.itemsize

4

In [ ]:
K.nbytes

12

In [7]:
arange_array=np.arange(100)

In [8]:
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a=np.arange(0,10,2)

In [ ]:
a

array([0, 2, 4, 6, 8])

In [ ]:
array_line=np.arange(0,10)

In [ ]:
array_line

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_line=np.linspace(0,10,10)

In [ ]:
array_line

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
len(array_line)

10

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((20),dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
t=np.empty([2,3])

In [ ]:
t

array([[4.99839168e-310, 0.00000000e+000, 6.63951306e-310],
       [2.22809558e-312, 2.14321575e-312, 6.63957689e-310]])

In [ ]:
t.shape

(2, 3)

In [ ]:
np.empty([2,2])

array([[4.99839102e-310, 0.00000000e+000],
       [4.99918711e-310, 4.99918711e-310]])

In [ ]:
np.full((3,3),201)

array([[201, 201, 201],
       [201, 201, 201],
       [201, 201, 201]])

In [ ]:
np.full((3,3),"sandeep")

array([['sandeep', 'sandeep', 'sandeep'],
       ['sandeep', 'sandeep', 'sandeep'],
       ['sandeep', 'sandeep', 'sandeep']], dtype='<U7')

In [ ]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
array_id=np.identity(4)

In [ ]:
array_id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
array_rand=np.random.rand (2,5)

In [ ]:
array_rand

array([[0.11723446, 0.86081696, 0.89493719, 0.60320659, 0.2232409 ],
       [0.90241417, 0.68118364, 0.33188274, 0.74889125, 0.58435764]])

In [ ]:
array_rand

array([[0.76782815, 0.86517665, 0.82657586],
       [0.29658734, 0.7334487 , 0.84878599]])

In [ ]:
array_rand=np.random.rand (3,4)

In [ ]:
array_rand

array([[0.1081494 , 0.14379506, 0.67564511, 0.80540326],
       [0.2337563 , 0.09778814, 0.8683719 , 0.44757618],
       [0.73285541, 0.90184586, 0.13200069, 0.89876857]])

In [ ]:
array_rand=np.random.rand (3,4,5)

In [ ]:
array_rand

array([[[0.24077237, 0.10633997, 0.09243255, 0.68726275, 0.56475909],
        [0.62474456, 0.19038257, 0.60962625, 0.71637764, 0.33242845],
        [0.69144221, 0.86231694, 0.3437691 , 0.10340927, 0.72027043],
        [0.12696255, 0.05292888, 0.10751276, 0.46629185, 0.81857071]],

       [[0.50321152, 0.56352575, 0.488466  , 0.37054477, 0.93151965],
        [0.87327044, 0.15391086, 0.21244243, 0.18885316, 0.4549383 ],
        [0.69587014, 0.49626985, 0.26690638, 0.10746798, 0.44156668],
        [0.90153371, 0.93731732, 0.23144122, 0.22694044, 0.37043316]],

       [[0.01648339, 0.99136905, 0.62941982, 0.22349743, 0.89322234],
        [0.36820263, 0.23470211, 0.02433672, 0.12336274, 0.39010105],
        [0.65232477, 0.72599556, 0.23800115, 0.29887597, 0.06325519],
        [0.93960567, 0.64220448, 0.65375915, 0.82738576, 0.03498826]]])

In [ ]:
array_rand=np.random.rand (3)

In [ ]:
array_rand

array([0.62483209, 0.78847344, 0.30765907])

In [ ]:
rand=np.random.randint(10,50,size=(5,2))

In [ ]:
rand

array([[38, 24],
       [14, 31],
       [47, 22],
       [42, 32],
       [17, 32]])

In [ ]:
rand

array([32, 12, 16, 43, 35])

In [ ]:
def func(i,j):
  return i+j
array=np.fromfunction(func,(3,3))
print(array)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [ ]:
it=range(40)
array_it=np.fromiter(iter(it),dtype=int)

In [ ]:
array_it

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
array_diag=np.diag([1,2,3])

In [ ]:
array_diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
array_in=np.array([10,20,30,40,50])

In [ ]:
array_in[0]

10

In [ ]:
array_in[3]

40

In [ ]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array_2d[0,0]

1

In [ ]:
array_2d[2,1]

8

In [ ]:
array_2d[1,1]

5

In [ ]:
k=np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
k[1:5:2]

array([1, 3])

In [ ]:
arr2d=np.arange(25).reshape(5,5)

In [ ]:
arr2d[::,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [ ]:
arr2d[0::4,::4]

array([[ 0,  4],
       [20, 24]])

In [ ]:
arr2d[1:3,0:2]

array([[ 5,  6],
       [10, 11]])

In [ ]:
arr2d[3::,3::]

array([[18, 19],
       [23, 24]])

In [ ]:
a=[[True,True,True,False,False,False]]

In [ ]:
a

[[True, True, True, False, False, False]]